// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Talent.API.Data;

#nullable disable

namespace Talent.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523204620_AddVacantesAndMarketplace")]
    partial class AddVacantesAndMarketplace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Talent.API.Entities.CategoriaSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("categorias_skill");
                });

            modelBuilder.Entity("Talent.API.Entities.Clase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_clase");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("ContenidoTexto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido_texto");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<long>("ModuloId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_modulo");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("video_url");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("clases");
                });

            modelBuilder.Entity("Talent.API.Entities.Diagnostico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_diagnostico");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("diagnosticos");
                });

            modelBuilder.Entity("Talent.API.Entities.Experiencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_experiencia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("empresa");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_perfil");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("experiencias");
                });

            modelBuilder.Entity("Talent.API.Entities.Modulo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_modulo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<long>("CategoriaSkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria_skill");

                    b.Property<string>("ContenidoUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("contenido_url");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("DuracionEstimada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("duracion_estimada");

                    b.Property<string>("NivelDificultad")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("nivel_dificultad");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaSkillId");

                    b.ToTable("modulos");
                });

            modelBuilder.Entity("Talent.API.Entities.ModuloSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ModuloId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_modulo");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_skill");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.HasIndex("SkillId");

                    b.ToTable("modulo_skills");
                });

            modelBuilder.Entity("Talent.API.Entities.OpcionPregunta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_opcion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<long>("PreguntaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_pregunta");

                    b.Property<int>("Puntaje")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("texto");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("opciones_pregunta");
                });

            modelBuilder.Entity("Talent.API.Entities.Perfil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_perfil");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("biografia");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titular");

                    b.Property<string>("UrlLinkedin")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("url_linkedin");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<bool>("VisibleMarketplace")
                        .HasColumnType("boolean")
                        .HasColumnName("visible_marketplace");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("perfiles");
                });

            modelBuilder.Entity("Talent.API.Entities.PerfilSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("nivel");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origen");

                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_perfil");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_skill");

                    b.Property<bool>("Validada")
                        .HasColumnType("boolean")
                        .HasColumnName("validada");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("SkillId");

                    b.ToTable("perfil_skills");
                });

            modelBuilder.Entity("Talent.API.Entities.PreguntaDiagnostico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_pregunta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("texto");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("preguntas_diagnostico");
                });

            modelBuilder.Entity("Talent.API.Entities.ProgresoClase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_progreso_clase");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_clase");

                    b.Property<bool>("Completado")
                        .HasColumnType("boolean")
                        .HasColumnName("completado");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_completado");

                    b.Property<long>("ProgresoModuloId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_progreso_modulo");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("ProgresoModuloId");

                    b.ToTable("progresos_clase");
                });

            modelBuilder.Entity("Talent.API.Entities.ProgresoModulo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_progreso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_completado");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<long>("ModuloId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_modulo");

                    b.Property<long>("RutaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_ruta");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.HasIndex("RutaId");

                    b.ToTable("progresos_modulo");
                });

            modelBuilder.Entity("Talent.API.Entities.RespuestaDiagnostico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_respuesta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DiagnosticoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_diagnostico");

                    b.Property<long>("OpcionId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_opcion");

                    b.Property<long>("PreguntaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_pregunta");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticoId");

                    b.HasIndex("OpcionId");

                    b.HasIndex("PreguntaId");

                    b.ToTable("respuestas_diagnostico");
                });

            modelBuilder.Entity("Talent.API.Entities.ResultadoDiagnostico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_resultado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria");

                    b.Property<long>("DiagnosticoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_diagnostico");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("nivel");

                    b.Property<int>("PuntajeMaximo")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje_maximo");

                    b.Property<int>("PuntajeObtenido")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje_obtenido");

                    b.Property<string>("Recomendacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("recomendacion");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DiagnosticoId");

                    b.ToTable("resultados_diagnostico");
                });

            modelBuilder.Entity("Talent.API.Entities.RutaAprendizaje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_ruta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DiagnosticoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_diagnostico");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("rutas_aprendizaje");
                });

            modelBuilder.Entity("Talent.API.Entities.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_skill");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("Talent.API.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contraseña");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Talent.API.Entities.Vacante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_vacante");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descripcion");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("modalidad");

                    b.Property<string>("RangoSalarial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rango_salarial");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ubicacion");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("vacantes");
                });

            modelBuilder.Entity("Talent.API.Entities.VacanteSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("NivelRequerido")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("nivel_requerido");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_skill");

                    b.Property<long>("VacanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_vacante");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("VacanteId");

                    b.ToTable("vacante_skills");
                });

            modelBuilder.Entity("Talent.API.Entities.Clase", b =>
                {
                    b.HasOne("Talent.API.Entities.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Talent.API.Entities.Diagnostico", b =>
                {
                    b.HasOne("Talent.API.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Talent.API.Entities.Experiencia", b =>
                {
                    b.HasOne("Talent.API.Entities.Perfil", "Perfil")
                        .WithMany("Experiencias")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Talent.API.Entities.Modulo", b =>
                {
                    b.HasOne("Talent.API.Entities.CategoriaSkill", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaSkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Talent.API.Entities.ModuloSkill", b =>
                {
                    b.HasOne("Talent.API.Entities.Modulo", "Modulo")
                        .WithMany("ModuloSkills")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talent.API.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Talent.API.Entities.OpcionPregunta", b =>
                {
                    b.HasOne("Talent.API.Entities.PreguntaDiagnostico", "Pregunta")
                        .WithMany("Opciones")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("Talent.API.Entities.Perfil", b =>
                {
                    b.HasOne("Talent.API.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Talent.API.Entities.PerfilSkill", b =>
                {
                    b.HasOne("Talent.API.Entities.Perfil", "Perfil")
                        .WithMany("PerfilSkills")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talent.API.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Talent.API.Entities.PreguntaDiagnostico", b =>
                {
                    b.HasOne("Talent.API.Entities.CategoriaSkill", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Talent.API.Entities.ProgresoClase", b =>
                {
                    b.HasOne("Talent.API.Entities.Clase", "Clase")
                        .WithMany()
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talent.API.Entities.ProgresoModulo", "ProgresoModulo")
                        .WithMany("ProgresosClase")
                        .HasForeignKey("ProgresoModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("ProgresoModulo");
                });

            modelBuilder.Entity("Talent.API.Entities.ProgresoModulo", b =>
                {
                    b.HasOne("Talent.API.Entities.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talent.API.Entities.RutaAprendizaje", "Ruta")
                        .WithMany("Progresos")
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("Talent.API.Entities.RespuestaDiagnostico", b =>
                {
                    b.HasOne("Talent.API.Entities.Diagnostico", "Diagnostico")
                        .WithMany("Respuestas")
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talent.API.Entities.OpcionPregunta", "Opcion")
                        .WithMany()
                        .HasForeignKey("OpcionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talent.API.Entities.PreguntaDiagnostico", "Pregunta")
                        .WithMany()
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diagnostico");

                    b.Navigation("Opcion");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("Talent.API.Entities.ResultadoDiagnostico", b =>
                {
                    b.HasOne("Talent.API.Entities.CategoriaSkill", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talent.API.Entities.Diagnostico", "Diagnostico")
                        .WithMany("Resultados")
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Diagnostico");
                });

            modelBuilder.Entity("Talent.API.Entities.RutaAprendizaje", b =>
                {
                    b.HasOne("Talent.API.Entities.Diagnostico", "Diagnostico")
                        .WithMany()
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talent.API.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnostico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Talent.API.Entities.Skill", b =>
                {
                    b.HasOne("Talent.API.Entities.CategoriaSkill", "Categoria")
                        .WithMany("Skills")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Talent.API.Entities.Vacante", b =>
                {
                    b.HasOne("Talent.API.Entities.Usuario", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Talent.API.Entities.VacanteSkill", b =>
                {
                    b.HasOne("Talent.API.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talent.API.Entities.Vacante", "Vacante")
                        .WithMany("VacanteSkills")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("Talent.API.Entities.CategoriaSkill", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Talent.API.Entities.Diagnostico", b =>
                {
                    b.Navigation("Respuestas");

                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("Talent.API.Entities.Modulo", b =>
                {
                    b.Navigation("ModuloSkills");
                });

            modelBuilder.Entity("Talent.API.Entities.Perfil", b =>
                {
                    b.Navigation("Experiencias");

                    b.Navigation("PerfilSkills");
                });

            modelBuilder.Entity("Talent.API.Entities.PreguntaDiagnostico", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("Talent.API.Entities.ProgresoModulo", b =>
                {
                    b.Navigation("ProgresosClase");
                });

            modelBuilder.Entity("Talent.API.Entities.RutaAprendizaje", b =>
                {
                    b.Navigation("Progresos");
                });

            modelBuilder.Entity("Talent.API.Entities.Vacante", b =>
                {
                    b.Navigation("VacanteSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
